# Generated by Django 2.2.4 on 2019-08-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190813_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
